StateEncoding:
  NONE: -1               # No Proprioceptive State
  POS_EULER: 1           # EEF XYZ (3) + Roll-Pitch-Yaw (3) + <PAD> (1) + Gripper Open/Close (1)
  POS_QUAT: 2            # EEF XYZ (3) + Quaternion (4) + Gripper Open/Close (1)
  JOINT: 3               # Joint Angles (7, <PAD> if fewer) + Gripper Open/Close (1)
  JOINT_BIMANUAL: 4      # Joint Angles (2 x [ Joint Angles (6) + Gripper Open/Close (1) ])

ActionEncoding:
  EEF_POS_4: 1            # EEF Delta XYZ (3) + Gripper Open/Close (1)
  EEF_POS_7: 2            # EEF Delta XYZ (3) + Roll-Pitch-Yaw (3) + Gripper Open/Close (1)
  JOINT_POS: 3            # Joint Delta Position (7) + Gripper Open/Close (1)
  JOINT_POS_BIMANUAL: 4   # Joint Delta Position (2 x [ Joint Delta Position (6) + Gripper Open/Close (1) ])
  EEF_VEL: 5              # EEF XYZ vel (3) + angular vel (3) + Gripper Open/Close (1)
  WHEELED: 6              # For wheeled robots

OPENX_DATASET_CONFIGS:
  fractal20220817_data:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - base_pose_tool_reached
      - gripper_closed
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 3
  
  kuka:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - clip_function_input/base_pose_tool_reached
      - gripper_closed
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 10
  
  bridge_openx:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - EEF_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 5
  
  taco_play:
    image_obs_keys:
      - rgb_static
      - rgb_gripper
    depth_obs_keys:
      - depth_static
      - depth_gripper
    state_obs_keys:
      - state_eef
      - state_gripper
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 15
  
  jaco_play:
    image_obs_keys:
      - image
      - image_wrist
    depth_obs_keys:
      - null
    state_obs_keys:
      - state_eef
      - state_gripper
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  berkeley_cable_routing:
    image_obs_keys:
      - image
      - top_image
      - wrist45_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - robot_state
    state_encoding: JOINT
    action_encoding: EEF_VEL
    fps: 10

  roboturk:
    image_obs_keys:
      - front_rgb
    depth_obs_keys:
      - null
    state_obs_keys:
      - null
    state_encoding: None
    action_encoding: EEF_POS_7
    fps: 10
  
  nyu_door_opening_surprising_effectiveness:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - null
    state_encoding: None
    action_encoding: EEF_POS_7
    fps: 3

  viola:
    image_obs_keys:
      - agentview_rgb
      - eye_in_hand_rgb
    depth_obs_keys:
      - null
    state_obs_keys:
      - joint_states
      - gripper_states
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 20

  berkeley_autolab_ur5:
    image_obs_keys:
      - image
      - hand_image
    depth_obs_keys:
      - image_with_depth
    state_obs_keys:
      - state
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 5

  toto:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: JOINT
    action_encoding: JOINT_POS
    fps: 30

  language_table:
    image_obs_keys:
      - rgb
    depth_obs_keys:
      - null
    state_obs_keys:
      - effector_translation
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10

  columbia_cairlab_pusht_real:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - robot_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10

  stanford_kuka_multimodal_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - depth_image
    state_obs_keys:
      - ee_position
      - ee_orientation
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 20

  nyu_rot_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 3

  io_ai_tech:
    image_obs_keys:
      - image
      - image_fisheye
      - image_left_side
      - image_right_side
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 3

  stanford_hydra_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10

  austin_buds_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 20

  nyu_franka_play_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - image_additional_view
    depth_obs_keys:
      - depth
      - depth_additional_view
    state_obs_keys:
      - eef_state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 3

  maniskill_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - depth
      - wrist_depth
    state_obs_keys:
      - tcp_pose
      - gripper_state
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 20

  furniture_bench_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_QUAT
    actionencoding: EEF_VEL
    fps: 10

  cmu_franka_exploration_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - highres_image
    depth_obs_keys:
      - null  
    state_obs_keys:
      - null
    state_encoding: NONE
    action_encoding: EEF_POS_7
    fps: 10

  ucsd_kitchen_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - joint_state
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 2
  
  ucsd_pick_and_place_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 3
  
  spoc:
    image_obs_keys:
      - image
      - image_manipulation
    depth_obs_keys:
      - null
    state_obs_keys:
      - null
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 3
  
  austin_sailor_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_QUAT
    action_encoding: EEF_VEL
    fps: 20
  
  austin_sirius_dataset_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_QUAT
    action_encoding: EEF_VEL
    fps: 20
  
  bc_z:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - present/xyz
      - present/axis_angle
      - present/sensed_close
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  utokyo_pr2_opening_fridge_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  utokyo_pr2_tabletop_manipulation_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  utokyo_xarm_pick_and_place_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - image2
      - hand_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - end_effector_pose
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  utokyo_xarm_bimanual_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - pose_r
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  robo_net:
    image_obs_keys:
      - image
      - image1
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 1
  
  robo_set:
    image_obs_keys:
      - image_left
      - image_right
      - image_wrist
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
      - state_velocity
    state_encoding: JOINT
    action_encoding: JOINT_POS
    fps: 5
  
  berkeley_mvp_converted_externally_to_rlds:
    image_obs_keys:
      - hand_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - gripper
      - pose
      - joint_pos
    state_encoding: POS_QUAT
    action_encoding: JOINT_POS
    fps: 5
  
  berkeley_rpt_converted_externally_to_rlds:
    image_obs_keys:
      - hand_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - joint_pos
      - gripper
    state_encoding: JOINT
    action_encoding: JOINT_POS
    fps: 30
  
  kaist_nonprehensile_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 10
  
  stanford_mask_vit_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
  
  tokyo_u_lsmo_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 10
  
  dlr_sara_pour_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 10
  
  dlr_sara_grid_clamp_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 10
  
  dlr_edan_shared_control_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 5
  
  asu_table_top_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 12.5

  stanford_robocook_converted_externally_to_rlds:
    image_obs_keys:
      - image_1
      - image_2
    depth_obs_keys:
      - depth_1
      - depth_2
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 5

  imperialcollege_sawyer_wrist_cam:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: NONE
    action_encoding: EEF_POS_7
    fps: 10

  iamlab_cmu_pickup_insert_converted_externally_to_rlds:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - joint_state
      - gripper_state
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 20

  uiuc_d3field:
    image_obs_keys:
      - image_1
      - image_2
    depth_obs_keys:
      - depth_1
      - depth_2
    state_obs_keys:
      - null
    state_encoding: NONE
    action_encoding: EEF_POS_7
    fps: 1
  
  utaustin_mutex:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 20
  
  berkeley_fanuc_manipulation:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - joint_state
      - gripper_state
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 10
  
  cmu_playing_with_food:
    image_obs_keys:
      - image
      - finger_vision_1
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  cmu_play_fusion:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: JOINT
    action_encoding: EEF_POS_7
    fps: 5
  
  cmu_stretch:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - eef_state
      - gripper_state
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 10
  
  berkeley_gnm_recon:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
      - position
      - yaw
    state_encoding: POS_EULER
    action_encoding: WHEELED
    fps: 3
 
  berkeley_gnm_cory_hall:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
      - position
      - yaw
    state_encoding: POS_EULER
    action_encoding: WHEELED
    fps: 5
 
  berkeley_gnm_sac_son:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
      - position
      - yaw
    state_encoding: POS_EULER
    action_encoding: WHEELED
    fps: 10
  
  droid:
    image_obs_keys:
      - exterior_image_1_left
      - exterior_image_2_left
      - wrist_image_left
    depth_obs_keys:
      - null
    state_obs_keys:
      - proprio
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 15
  
  droid_100:
    image_obs_keys:
      - exterior_image_1_left
      - exterior_image_2_left
      - wrist_image_left
    depth_obs_keys:
      - null
    state_obs_keys:
      - proprio
    state_encoding: POS_QUAT
    action_encoding: EEF_POS_7
    fps: 15
  
  fmb:
    image_obs_keys:
      - image_side_1
      - image_side_2
      - image_wrist_1
      - image_wrist_2
    depth_obs_keys:
      - image_side_1_depth
      - image_side_2_depth
      - image_wrist_1_depth
      - image_wrist_2_depth
    state_obs_keys:
      - proprio
    state_encoding: POS_EULER
    action_encoding: EEF_VEL
    fps: 10
  
  dobbe:
    image_obs_keys:
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - proprio
    state_encoding: POS_EULER
    action_encoding: EEF_POS_7
    fps: 3.75
  
  usc_cloth_sim_converted_externally_to_rlds:
    image_obs_keys:
      - image
    depth_obs_keys:
      - null
    state_obs_keys:
      - null
    state_encoding: NONE
    action_encoding: EEF_POS_4
    fps: 10
  
  plex_robosuite:
    image_obs_keys:
      - image
      - wrist_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: NONE
    action_encoding: EEF_POS_7
    fps: 20
  
  conq_hose_manipulation:
    image_obs_keys:
      - frontleft_fisheye_image
      - frontright_fisheye_image
      - hand_color_image
    depth_obs_keys:
      - null
    state_obs_keys:
      - state
    state_encoding: NONE
    action_encoding: EEF_VEL
    fps: 30
  